// Code generated by hertz generator.

package routers

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"tiktok-gateway/internal/handler"
	"tiktok-gateway/internal/middleware"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	group := r.Group("/douyin")

	group.POST("/user/register", handler.Ping)
	group.POST("/user/login", handler.Ping)

	auth := group.Group("/user", middleware.JwtMiddleware.MiddlewareFunc())
	auth.GET("/", handler.Ping)

	auth = group.Group("/relation", middleware.JwtMiddleware.MiddlewareFunc())
	auth.POST("/action", handler.Ping)
	auth.GET("/follow/list", handler.Ping)
	auth.GET("/follower/list", handler.Ping)
	auth.GET("/friend/list", handler.Ping)
}
