// Code generated by hertz generator.

package routers

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	handler "tiktok-gateway/internal/handler"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	r.GET("/ping", handler.Ping)

	// your code ...
}
