// Code generated by hertz generator.

package routers

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	"tiktok-gateway/internal/handler"
	"tiktok-gateway/internal/middleware"
)

// customizeRegister registers customize routers.
func customizedRegister(r *server.Hertz) {
	group := r.Group("/relation")
	group.POST("/user/register", handler.DouyinUserRegisterMethod)
	group.POST("/user/login", middleware.JwtMiddleware.LoginHandler)
	auth := group.Group("/user", middleware.JwtMiddleware.MiddlewareFunc())
	auth.GET("/", handler.DouyinUserMethod)
	auth = group.Group("/relation", middleware.JwtMiddleware.MiddlewareFunc())
	auth.POST("/action", handler.DouyinUserMethod)
	auth.GET("/follow/list", handler.DouyinUserMethod)
	auth.GET("/follower/list", handler.DouyinUserMethod)
	auth.GET("/friend/list", handler.DouyinUserMethod)
}
