// Code generated by hertz generator.

package main

import (
	"github.com/cloudwego/hertz/pkg/app/server"
	routers "tiktok-gateway/internal/routers"
)

func main() {
	h := server.Default()

	routers.Register(h)
	h.Spin()
}
