// Code generated by hertz generator.

package handler

import (
	"context"
	"github.com/cloudwego/hertz/pkg/app"
	"github.com/cloudwego/hertz/pkg/protocol/consts"
	"github.com/cloudwego/kitex/client"
	etcd "github.com/kitex-contrib/registry-etcd"
	"log"
	"tiktok-gateway/kitex_gen/user"
	"tiktok-gateway/kitex_gen/user/douyinservice"
	"time"
)

func DouyinUserRequest(ctx context.Context, c *app.RequestContext) {
	var RegisterInfo user.DouyinUserRegisterRequest
	err := c.BindAndValidate(&RegisterInfo)
	log.Print(RegisterInfo)
	if err != nil {
		log.Fatal("Bind ERROR")
	}

	r, err := etcd.NewEtcdResolver([]string{"127.0.0.1:2379"})
	if err != nil {
		log.Fatal(err)
	}

	client, err := douyinservice.NewClient("user", client.WithResolver(r))
	if err != nil {
		log.Fatal(err)
	}
	ctx, cancel := context.WithTimeout(context.Background(), time.Second*3)
	resp, err := client.DouyinUserRegisterMethod(ctx, &RegisterInfo)
	cancel()
	if err != nil {
		log.Fatal(err)
	}
	c.JSON(consts.StatusOK, resp)

}
